export const mockPatients = {
  patients: [
    {
      id: '1',
      firstName: 'Tony',
      lastName: 'Brinton',
      dob: '06-25-2008',
      implants: [
        {
          treatmentDate: '8-7-23',
          toothNumber: '2',
          manufacturer: 'Manufacturer A',
          implantType: 'Type A',
          implantSize: 'Medium',
          notes: 'First implant',
          treatingDoc: 'Dr. A',
          referringDoc: 'Dr. B',
        },
        {
          treatmentDate: '4-16-21',
          toothNumber: '4',
          manufacturer: 'Manufacturer B',
          implantType: 'Type B',
          implantSize: 'Large',
          notes: 'Second implant',
          treatingDoc: 'Dr. C',
          referringDoc: 'Dr. D',
        },
        {
          treatmentDate: '3-7-18',
          toothNumber: '6',
          manufacturer: 'Manufacturer A',
          implantType: 'Type A',
          implantSize: 'Small',
          notes: 'Third implant',
          treatingDoc: 'Dr. E',
          referringDoc: 'Dr. F',
        },
      ],
    },
    {
      id: '2',
      firstName: 'Steve',
      lastName: 'Rogers',
      dob: '07-04-1980',
      implants: [
        {
          treatmentDate: '5-12-22',
          toothNumber: '3',
          manufacturer: 'Manufacturer C',
          implantType: 'Type C',
          implantSize: 'Large',
          notes: 'Implant for tooth 3',
          treatingDoc: 'Dr. G',
          referringDoc: 'Dr. H',
        },
        {
          treatmentDate: '8-15-20',
          toothNumber: '7',
          manufacturer: 'Manufacturer A',
          implantType: 'Type A',
          implantSize: 'Medium',
          notes: 'Implant for tooth 7',
          treatingDoc: 'Dr. I',
          referringDoc: 'Dr. J',
        },
      ],
    },
    {
      id: '3',
      firstName: 'Jack',
      lastName: 'Wick',
      dob: '08-30-1998',
      implants: [
        {
          treatmentDate: '5-12-22',
          toothNumber: '3',
          manufacturer: 'Manufacturer D',
          implantType: 'Type D',
          implantSize: 'Small',
          notes: 'Additional implant for tooth 3',
          treatingDoc: 'Dr. K',
          referringDoc: 'Dr. L',
        },
        {
          treatmentDate: '8-15-20',
          toothNumber: '7',
          manufacturer: 'Manufacturer E',
          implantType: 'Type E',
          implantSize: 'Large',
          notes: 'Additional implant for tooth 7',
          treatingDoc: 'Dr. M',
          referringDoc: 'Dr. N',
        },
      ],
    },
    {
      id: '4',
      firstName: 'Tony',
      lastName: 'Brinton',
      dob: '6-25-2008',
      implants: [
        {
          treatmentDate: '5-12-22',
          toothNumber: '3',
          manufacturer: 'Manufacturer F',
          implantType: 'Type F',
          implantSize: 'Medium',
          notes: 'Implant for tooth 3',
          treatingDoc: 'Dr. O',
          referringDoc: 'Dr. P',
        },
        {
          treatmentDate: '8-15-20',
          toothNumber: '7',
          manufacturer: 'Manufacturer G',
          implantType: 'Type G',
          implantSize: 'Small',
          notes: 'Implant for tooth 7',
          treatingDoc: 'Dr. Q',
          referringDoc: 'Dr. R',
        },
      ],
    },
    {
      id: '5',
      firstName: 'Tony',
      lastName: 'Brinton',
      dob: '6-25-2008',
      implants: [
        {
          treatmentDate: '5-12-22',
          toothNumber: '3',
          manufacturer: 'Manufacturer H',
          implantType: 'Type H',
          implantSize: 'Large',
          notes: 'Implant for tooth 3',
          treatingDoc: 'Dr. S',
          referringDoc: 'Dr. T',
        },
        {
          treatmentDate: '8-15-20',
          toothNumber: '7',
          manufacturer: 'Manufacturer I',
          implantType: 'Type I',
          implantSize: 'Medium',
          notes: 'Implant for tooth 7',
          treatingDoc: 'Dr. U',
          referringDoc: 'Dr. V',
        },
      ],
    },
  ],
  total: 5,
};
